# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: fossil
# Description of the Site
description: Social media optimized for you
# URL of Image of the Site
site-image: /assets/images/logo-mid.svg
# Keywords of the Site
site-keywords: Social Media, Mastodon, Fediverse, Time Management
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

app-url: https://app.fossil-social.com/

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/540123_1920.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
# email: thedevslot@gmail.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
# linkedin_username: thedevslot
github_username:  kelloggt
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-H632KPLKBM

# Disqus
disqus-shortname: ""

# Name of the Author
author-name: Tim Kellogg
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832_960_720.jpg
# 60 Words About the Author
author-about: CEO and founder of Kellogg Software, LLC
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://timkellogg.me

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
